countries_to_urls = {'Argentina': 'https://ar.indeed.com/',
 'Australia': 'https://au.indeed.com/',
 'Austria': 'https://at.indeed.com/',
 'Bahrain': 'https://bh.indeed.com/',
 'Belgium': 'https://be.indeed.com/',
 'Brazil': 'https://www.indeed.com.br/',
 'Canada': 'https://ca.indeed.com/',
 'Chile': 'https://cl.indeed.com/',
 'China': 'https://cn.indeed.com/',
 'Colombia': 'https://co.indeed.com/',
 'Costa Rica': 'https://cr.indeed.com/',
 'Czech Republic': 'https://cz.indeed.com/',
 'Denmark': 'https://dk.indeed.com/',
 'Ecuador': 'https://ec.indeed.com/',
 'Egypt': 'https://eg.indeed.com/',
 'Finland': 'https://fi.indeed.com/',
 'France': 'https://www.indeed.fr/',
 'Germany': 'https://de.indeed.com/',
 'Greece': 'https://gr.indeed.com/',
 'Hong Kong': 'https://hk.indeed.com/',
 'Hungary': 'https://hu.indeed.com/',
 'India': 'https://www.indeed.co.in/',
 'Indonesia': 'https://id.indeed.com/',
 'Ireland': 'https://ie.indeed.com/',
 'Israel': 'https://il.indeed.com/',
 'Italy': 'https://it.indeed.com/',
 'Japan': 'https://jp.indeed.com/',
 'Kuwait': 'https://kw.indeed.com/',
 'Luxembourg': 'https://lu.indeed.com/',
 'Malaysia': 'https://malaysia.indeed.com/',
 'Mexico': 'https://www.indeed.com.mx/',
 'Morocco': 'https://ma.indeed.com/',
 'Netherlands': 'https://www.indeed.nl/',
 'New Zealand': 'https://nz.indeed.com/',
 'Nigeria': 'https://ng.indeed.com/',
 'Norway': 'https://no.indeed.com/',
 'Oman': 'https://om.indeed.com/',
 'Pakistan': 'https://pk.indeed.com/',
 'Panama': 'https://pa.indeed.com/',
 'Peru': 'https://pe.indeed.com/',
 'Philippines': 'https://ph.indeed.com/',
 'Poland': 'https://pl.indeed.com/',
 'Portugal': 'https://pt.indeed.com/',
 'Qatar': 'https://qa.indeed.com/',
 'Romania': 'https://ro.indeed.com/',
 'Russia': 'https://ru.indeed.com/',
 'Saudi Arabia': 'https://sa.indeed.com/',
 'Singapore': 'https://sg.indeed.com/',
 'South Africa': 'https://za.indeed.com/',
 'South Korea': 'https://kr.indeed.com/',
 'Spain': 'https://es.indeed.com/',
 'Sweden': 'https://se.indeed.com/',
 'Switzerland': 'https://www.indeed.ch/',
 'Taiwan': 'https://tw.indeed.com/',
 'Thailand': 'https://th.indeed.com/',
 'Turkey': 'https://tr.indeed.com/',
 'Ukraine': 'https://ua.indeed.com/',
 'United Arab Emirates': 'https://www.indeed.ae/',
 'United Kingdom': 'https://www.indeed.co.uk/',
 'Uruguay': 'https://uy.indeed.com/',
 'Venezuela': 'https://ve.indeed.com/',
 'Vietnam': 'https://vn.indeed.com/'}



countries = countries_to_urls.keys()







